#!/bin/bash

# Function to fetch a random joke from icanhazdadjoke.com API
fetch_joke() {
    joke=$(curl -sH "Accept: text/plain" https://icanhazdadjoke.com/)
    echo "$joke"
}

# Function to print a joke with specified options
print_joke() {
    local joke="$1"
    local color="$2"
    local large_font="$3"
    local speech_bubble="$4"

    local cowsay_path="/opt/homebrew/Cellar/cowsay/3.04_1/share/cows/"

    if [[ "$speech_bubble" == "true" ]]; then
        if [ -d "$cowsay_path" ]; then
            if [[ "$color" == "true" ]]; then
                if [[ "$large_font" == "true" ]]; then
                    echo "$joke" | figlet | lolcat | cowsay -n -f "$(ls "$cowsay_path" | shuf -n 1)" | lolcat
                else
                    echo "$joke" | cowsay -n -f "$(ls "$cowsay_path" | shuf -n 1)" | lolcat
                fi
            else
                if [[ "$large_font" == "true" ]]; then
                    echo "$joke" | figlet | cowsay -n -f "$(ls "$cowsay_path" | shuf -n 1)"
                else
                    echo "$joke" | cowsay -n -f "$(ls "$cowsay_path" | shuf -n 1)"
                fi
            fi
        else
            echo "Error: Cowsay cowfiles directory not found at $cowsay_path"
        fi
    elif [[ "$color" == "true" ]]; then
        if [[ "$large_font" == "true" ]]; then
            echo "$joke" | figlet | lolcat
        else
            echo "$joke" | lolcat
        fi
    elif [[ "$large_font" == "true" ]]; then
        echo "$joke" | figlet
    else
        echo "$joke"
    fi
}

# Main script

# Initialize flags
color="false"
large_font="false"
speech_bubble="false"

# Parse command line flags
while getopts "cfl" opt; do
    case ${opt} in
        c ) color="true";;
        f ) large_font="true";;
        l ) speech_bubble="true";;
        \? ) echo "Usage: $(basename $0) [-c] [-f] [-l]"
             echo "Options:"
             echo "  -c    Print joke in color"
             echo "  -f    Print joke in large font"
             echo "  -l    Print joke inside a speech bubble"
             exit 1;;
    esac
done

# Fetch a random joke
joke=$(fetch_joke)

# Print the joke with specified options
print_joke "$joke" "$color" "$large_font" "$speech_bubble"
